#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config pointer_action1     move

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled

feh --bg-fill ~/Pictures/tpe.png

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh
